[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lucky_trading = "ATnAJWbLWJHc3qCb7ai4cSiWgaUFXqMhmZs7qQfSHxsX"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet" # Devnet, Localnet, Mainnet
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test_local.ts"
create_vault = "ts-node scripts/create_vault.ts"
[test]
startup_wait = 2000